### ISSUE TITLE
The type or namespace DigipostClient could not be found

### ISSUE THREAD

**Issue by natsuo** [digipost/digipost-api-client-dotnet#158]
Nyaamaste.

I've tried to use Digipost nuget packages (9.0.1 and 9.0.0) with a netcoreapp2.0 class library. I've added the package references to `Digipost.Api.Client.Send` and `Digipost.Api.Client.Inbox`.

I used the examples in the Digipost.Api.Client.Docs folder, but I have a working app using the version 8.3.0 .NET Framework library that uses similar code.

```csharp
using Digipost.Api.Client;
using Digipost.Api.Client.Common;
using DigiEnv = Digipost.Api.Client.Common.Environment;

...

var broker = new Broker(_userId);
var config = new ClientConfig(broker, DigiEnv.Production);
_client = new DigipostClient(config, "8badf00d");
```

Resulting in the error:
`error CS0246: The type or namespace name 'DigipostClient' could not be found`

The same code compiles in the old 8.3.0 client.

Are there any known issues with the 9.0.1 nuget package?

**Comment by AaronArrick** [comment]
Hey there, sorry for the delayed response! After some digging I realised Nuget doesn't seem to have the Digipost.Api.Client core package for some reason. I'm working on getting a new release out ASAP.

**Comment by natsuo** [comment]
Thank you, much appreciated. 😸

**Comment by natsuo** [comment]
Version `9.0.3-beta1` fixes the problem. Thank you!

**Comment by AaronArrick** [comment]
The final version of 9.0.3 is out now! Glad to hear it worked! Thanks a bunch for your patience. 👍
